version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app_development
      - MYSQL_ROOT_PASSWORD=checkout_passwd
    volumes:
      - mysql-datavolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis:3.2.4
    container_name: redis
    ports:
      - "6379:6379"

  mocks:
    build: ../mocks
    ports:
      - "8083:8083"

volumes:
  mysql-datavolume: